name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          cd front_ctrl-alt-defeat
          npm install --save-dev @babel/plugin-proposal-private-property-in-object
          npm install

      - name: Build React app
        run: |
          cd front_ctrl-alt-defeat
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build # Este job depende da conclusão bem-sucedida do job de build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          cd front_ctrl-alt-defeat
          vercel --prod
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

