name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          cd front_ctrl-alt-defeat
          npm i

      - name: Build React app
        run: |
          cd front_ctrl-alt-defeat
          npm run build

      - name: Start JSON Server
        run: | 
          cd front_ctrl-alt-defeat
          npm run server
